Enrollment No.: 240840116029

Practical-3: Apply ƒiltering, sorting, aggregation, and GroupBy operations on real-world datasets.

In [ ]:
#Pandas is used to create, read, modify, and analyze tabular data.
import pandas as pd

In [ ]:
#add data
data = {
    "Emp_ID":[101,102,103,104,105,106,107,108],
    "Name":["Rahul","Priya","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department":["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City":["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000,38000,52000,48000,40000,51000,60000,42000],
    "Experience":[2,1,5,4,2,6,8,3]
}

Step 1 : Display the Dataset

In [ ]:
#Convert the dictionary into a Pandas DataFrame for easier data manipulation
df = pd.DataFrame(data)
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

Step 2 : Filter Data

In [ ]:
#Select only employees working is the IT department
df[df["Department"]=="IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Display Employees with salary greater than 50,000

In [ ]:
#Display the employees whos salary is greater than 50000
df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

Display employees from Surat

In [ ]:
#Display employees from Surat
df[df["City"]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

Apply Multiple Conditions

In [ ]:
#display employee from the IT department
#having salary greater than 50000
df[(df["Department"]=="IT") & (df["Salary"]>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

Step 3 : Sort Data

Sort Salary in Ascending Order

In [ ]:
#Sort employee by salary from lowest to highest.
df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

Sort salary in Descending Order

In [ ]:
#Sort employee by salary from higest to lowest
df.sort_values(by="Salary",ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

Sort by Department and Salary

In [ ]:
#First sort by department within each department sort salaries in descending order
df.sort_values(by=["Department","Salary"], ascending=[True,False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

Step 4 : Perform Aggeregation

Calculate Total Salary

In [ ]:
# Calculate the total salary
df["Salary"].sum()

np.int64(376000)

Calculate Average salary

In [ ]:
#Calculate Average salary
df["Salary"].mean()

np.float64(47000.0)

Find highest salary

In [ ]:
#Display maxium salary
df["Salary"].max()

60000

Find Lowest Salary

In [ ]:
#Display the minimum salary
df["Salary"].min()

38000

Count Employees

In [ ]:
# Count the total numbers of employees
df["Emp_ID"].count()

np.int64(8)

Step 5 : Perform GroupBy Operation

Average Salary department-wise

In [ ]:
# Group employees based on department
df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

Minimum Salary Department-wise

In [ ]:
#Minimum Salary Department-wise
df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

Count Salary Department-wise

In [ ]:
#Count Salary Department-wise
df.groupby("Department")["Salary"].count()

Department
Finance    2
HR         3
IT         3
Name: Salary, dtype: int64

Total salary Department-wise

In [ ]:
# Calculate the total salary paid by each department
df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

Maximum salary department-wise

In [ ]:
#Maximum salary department-wise
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

Average salary City-wise

In [ ]:
#Average salary City-wise
df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

Step 6: Multiple Aggregation Function

In [ ]:
#Multiple Aggregation Function
df.groupby("Department")["Salary"].agg(["count","sum","min","max"])

            count     sum    min    max
Department
Finance         2   99000  48000  51000
HR              3  120000  38000  42000
IT              3  157000  45000  60000

Step 7 : Save the data

In [ ]:
# Save the data
df.to_csv("Employee_data.csv",index=False)
print("Data saved sucessfully.")

Data saved sucessfully.