Enrollment No.: 240840116029

Practical-1: Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON ƒiles using Pandas.

Step 1: Import the Pandas library

In [ ]:
#Pandas is used to create, read, modify, and analyze tabular data.
import pandas as pd

Step 2: Create sample data

In [ ]:
# Create a dictionary containing student details such as ID, Name, Age, City, and Marks.
data = {
    "ID":[101,102,103,104,105,106,107],
    "NAME":["Rahul","Priya","Amit","Riya","Karan","Krisha","Harry"],
    "Age":[20,21,19,20,22,24,28],
    "City":["Surat","Navasari","Valsad","Bharuch","Surat","Gandhinagar","Ahmedabad"],
    "Marks":[85,92,78,88,81,84,90]
}

Step 3: Create a DataFrame

In [ ]:
#Convert the dictionary into a Pandas DataFrame for easier data manipulation.
df = pd.DataFrame(data)
df

    ID    NAME  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21     Navasari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 4: Save data as a CSV file

In [ ]:
#Export the DataFrame to a CSV file without including the index column.
df.to_csv("students.csv",index=False)
print("CSV file created successfully.")

CSV file created successfully.

Step 5: Save data as an Excel file

In [ ]:
#Export the DataFrame to an Excel (.xlsx) file.
df.to_excel("students.xlsx",index=False)
print("Excel file created successfully.")

Excel file created successfully.

Step 6: Save data as a JSON file

In [ ]:
#Export the DataFrame to a JSON file using record-oriented format.
df.to_json("students.json",orient="records",indent=4)
print("JSON file created successfully.")

JSON file created successfully.

Step 7: Read the CSV file

In [ ]:
#Load the CSV file back into a DataFrame.
df_csv = pd.read_csv("students.csv")
df_csv

    ID    NAME  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21     Navasari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 8: Read the Excel file

In [ ]:
#Load the Excel file into a DataFrame.
df_excel = pd.read_excel("students.xlsx")
df_excel

    ID    NAME  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21     Navasari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 9: Read the JSON file

In [ ]:
#Load the JSON file into a DataFrame.
df_json = pd.read_json("students.json")
df_json

    ID    NAME  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21     Navasari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 10: Display the first five records

In [ ]:
#View the first five rows of the dataset using head().
df_csv.head()

    ID   NAME  Age      City  Marks
0  101  Rahul   20     Surat     85
1  102  Priya   21  Navasari     92
2  103   Amit   19    Valsad     78
3  104   Riya   20   Bharuch     88
4  105  Karan   22     Surat     81

Step 11: Display the last five records

In [ ]:
#View the last five rows of the dataset using tail().
df_csv.tail()

    ID    NAME  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 12: Display dataset information

In [ ]:
#Show the number of rows, columns, data types, and non-null values.
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   NAME    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Step 13: Display statistical summary

In [ ]:
#Generate summary statistics such as count, mean, minimum, maximum, and standard deviation.
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

Step 14: Display dataset shape

In [ ]:
#Show the total number of rows and columns in the dataset.
df_csv.shape

(7, 5)

Step 15: Display column names

In [ ]:
#List all the column names present in the DataFrame.
df_csv.columns

Index(['ID', 'NAME', 'Age', 'City', 'Marks'], dtype='object')

Step 16: Display data types

In [ ]:
#Show the data type of each column.
df_csv.dtypes

ID        int64
NAME     object
Age       int64
City     object
Marks     int64
dtype: object

Step 17: Check for missing values

In [ ]:
#Count the number of missing (null) values in each column.
df_csv.isnull().sum()

ID       0
NAME     0
Age      0
City     0
Marks    0
dtype: int64

Step 18: Display a single column

In [ ]:
#Retrieve and display only the 'Name' column.
df_csv["Marks"]

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

Step 19: Display multiple columns

In [ ]:
#Retrieve and display the 'Name' and 'Marks' columns together.
df_csv[['NAME','Marks']]

     NAME  Marks
0   Rahul     85
1   Priya     92
2    Amit     78
3    Riya     88
4   Karan     81
5  Krisha     84
6   Harry     90

Step 20: Filter records

In [ ]:
#Display only the students whose marks are greater than 80.
df_csv[df_csv["Marks"]>80]

    ID    NAME  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21     Navasari     92
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

Step 21: Calculate average marks

In [ ]:
#Compute the average (mean) marks of all students.
df_csv["Marks"].mean()

np.float64(85.42857142857143)

Step 22: Sort data

In [ ]:
#Arrange the student records in descending order based on marks.
df_csv.sort_values(by="Marks",ascending=False)

    ID    NAME  Age         City  Marks
1  102   Priya   21     Navasari     92
6  107   Harry   28    Ahmedabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78