Enrollment No.: 240840116029

Practical - 2 : Perform data inspection, cleaning, handling missing values, duplicate removal and data transformation using pandas.

 Step : 1 import pandas

In [ ]:
#import pandas
import pandas as pd

Step : 2 Create a dataset

In [ ]:
#add data
data = {
    "ID":[101,102,103,104,104,105,106,107],
    "Name":["Rahul","Priya","Amit",None,"Riya","Ajay","Naresh","Jenil"],
    "Age":[20,21,None,20,20,22,23,28],
    "City":["Surat","Navsari","Surat","Bharuch","Bharuch","Navsari","Baroda","Ahmedabad"],
    "Marks":[85,None,78,88,88,81,90,93]
}

In [ ]:
df = pd.DataFrame(data)
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0     Baroda   90.0
7  107   Jenil  28.0  Ahmedabad   93.0

Step : 3 Inspect the dataset

In [ ]:
#Display first five row of dataset.
df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [ ]:
#display last five row of dataset
df.tail()

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0     Baroda   90.0
7  107   Jenil  28.0  Ahmedabad   93.0

In [ ]:
# display detail information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
#generate statistical information for numerical colums
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [ ]:
#display dimention of dataset
#output format( Number of row, Number of column)
df.shape

(8, 5)

In [ ]:
#display the name of all columns in the dataframe
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [ ]:
#display the data type of each column
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

Step 4 : Check missing values

In [ ]:
#check for missing value in each column
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

Step 5 : Replace missing values

In [ ]:
#replace missing values in the marks column
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0     Baroda  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [ ]:
#replace missing values in the age column
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0     Baroda  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

In [ ]:
#replace missing names with the next "unknown"
df["Name"] = df["Name"].fillna("unknown")
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0     Baroda  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

Step 6 : Check whether

In [ ]:
#check whether each show is duplicated.
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [ ]:
#count total number of duplicate rows.
df.duplicated().sum()

np.int64(0)

Step 7 : Remove duplicate records.

In [ ]:
#Remove duplicate rows from the data frame.
df = df.drop_duplicates()
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0     Baroda  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

Step 8: Rename a column

In [ ]:
#Rename the column "Marks" to "Score"
df.rename(columns = {"Marks" : "Score"}, inplace = True)
df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0     Baroda  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

Step 9 : Change data type.

In [ ]:
#Convert the age column from float to integer.
df["Age"]=df["Age"].astype(int)
df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

Step 10 : Create a new column.

In [ ]:
#Create a new column "Final Score"
df["Final Score"] = df["Score"] = 5
df

    ID     Name  Age       City  Score  Final Score
0  101    Rahul   20      Surat      5            5
1  102    Priya   21    Navsari      5            5
2  103     Amit   22      Surat      5            5
3  104  unknown   20    Bharuch      5            5
4  104     Riya   20    Bharuch      5            5
5  105     Ajay   22    Navsari      5            5
6  106   Naresh   23     Baroda      5            5
7  107    Jenil   28  Ahmedabad      5            5

Step 11 : Convert a student name

In [ ]:
#Convert all student names to Uppercase.
df["Name"] = df["Name"].str.upper()
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      Surat      5            5
1  102    PRIYA   21    Navsari      5            5
2  103     AMIT   22      Surat      5            5
3  104  UNKNOWN   20    Bharuch      5            5
4  104     RIYA   20    Bharuch      5            5
5  105     AJAY   22    Navsari      5            5
6  106   NARESH   23     Baroda      5            5
7  107    JENIL   28  Ahmedabad      5            5

Step 12 : Convert text to lowercase

In [ ]:
# Convert City names to lowercase
df["City"] = df["City"].str.lower()
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      surat      5            5
1  102    PRIYA   21    navsari      5            5
2  103     AMIT   22      surat      5            5
3  104  UNKNOWN   20    bharuch      5            5
4  104     RIYA   20    bharuch      5            5
5  105     AJAY   22    navsari      5            5
6  106   NARESH   23     baroda      5            5
7  107    JENIL   28  ahmedabad      5            5

Step 13 : Remove extra spaces

In [ ]:
# Remove extra spaces from Name column
df["City"] = df["City"].str.strip()
df

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      surat      5            5
1  102    PRIYA   21    navsari      5            5
2  103     AMIT   22      surat      5            5
3  104  UNKNOWN   20    bharuch      5            5
4  104     RIYA   20    bharuch      5            5
5  105     AJAY   22    navsari      5            5
6  106   NARESH   23     baroda      5            5
7  107    JENIL   28  ahmedabad      5            5

Step 14 : sort the dataset

In [ ]:
#sort the dataframe based on the "Final Score" column.
df.sort_values(by = "Final Score", ascending = False)

    ID     Name  Age       City  Score  Final Score
0  101    RAHUL   20      surat      5            5
1  102    PRIYA   21    navsari      5            5
2  103     AMIT   22      surat      5            5
3  104  UNKNOWN   20    bharuch      5            5
4  104     RIYA   20    bharuch      5            5
5  105     AJAY   22    navsari      5            5
6  106   NARESH   23     baroda      5            5
7  107    JENIL   28  ahmedabad      5            5

Step 15 : Save the cleaned dataset

In [ ]:
#Save the cleaned dataframe as a new CSV file
df.to_csv("Cleaned_Students.csv",index=False)
print("Dataset Saved Successfully.")

Dataset Saved Successfully.

.